### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by arnyeinstein** [swiss-adminR/pkgs#4]
Hi
The link "admindown: CD-Bund Compatible R Markdown Theme" is not working.
Cheers
Renger

**Comment by christophsax** [comment]
I checked and you should have access:

<img width="361" alt="image" src="https://user-images.githubusercontent.com/1390827/133325314-8cb007ea-b647-4992-9a81-2cb63b63c3bc.png">

This LInk is not working?

https://github.com/swiss-adminR/admindown

Are you logged into GitHub?

**Comment by arnyeinstein** [comment]
That was the problem. Thanks!
